# Generated by Django 4.2.30 on 2026-08-11 22:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consignment_number', models.CharField(max_length=30)),
                ('sent_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسلة'), ('partial_returned', 'مرتجع جزئي'), ('settled', 'تمت التسوية'), ('cancelled', 'ملغية')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('settled_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignments', to='customers.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignments', to='sales.invoice')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_consignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_sent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_returned', models.PositiveIntegerField(default=0)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consignment_items', to='inventory.batch')),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consignments.consignment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_items', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConsignmentReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='consignments.consignment')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_consignment_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsignmentReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_returned', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('consignment_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='consignments.consignmentitem')),
                ('consignment_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consignments.consignmentreturn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='consignment',
            constraint=models.UniqueConstraint(fields=('company', 'consignment_number'), name='uniq_consignment_per_company'),
        ),
    ]
