# Generated by Django 4.2.30 on 2026-08-11 21:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('core', '0001_initial'),
        ('products', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('return_number', models.CharField(max_length=20)),
                ('return_date', models.DateField()),
                ('return_reason', models.CharField(choices=[('near_expiry', 'قرب انتهاء صلاحية'), ('damaged', 'منتج تالف'), ('wrong_delivery', 'خطأ في التوريد'), ('customer_request', 'طلب العميل'), ('batch_recall', 'سحب تشغيلة'), ('other', 'أخرى')], max_length=30)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'معتمد'), ('received', 'مستلم بالمخزن'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='sales.invoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'returns',
                'ordering': ['-return_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_condition', models.CharField(choices=[('good', 'صالح للبيع'), ('damaged', 'تالف'), ('expired', 'منتهي الصلاحية')], default='good', max_length=20)),
                ('disposition', models.CharField(choices=[('return_to_stock', 'إعادة للمخزن'), ('destroy', 'إتلاف'), ('quarantine', 'حجر صحي')], default='return_to_stock', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.batch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('return_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return')),
            ],
            options={
                'db_table': 'return_items',
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credit_note_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('issued', 'صادر'), ('applied', 'مطبق'), ('cancelled', 'ملغي')], default='issued', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('applied_to_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_credit_notes', to='sales.invoice')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='customers.customer')),
                ('return_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note', to='returns.return')),
            ],
            options={
                'db_table': 'credit_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='return',
            constraint=models.UniqueConstraint(fields=('company', 'return_number'), name='uniq_return_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(fields=('company', 'credit_note_number'), name='uniq_credit_note_per_company'),
        ),
    ]
