# Generated by Django 4.2.30 on 2026-08-11 20:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=30)),
                ('quantity_received', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_defective', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('production_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('received', 'مستلمة'), ('approved', 'معتمدة للبيع'), ('held', 'محجوزة'), ('expired', 'منتهية'), ('depleted', 'نفدت')], default='approved', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
            ],
            options={
                'db_table': 'batches',
                'ordering': ['expiry_date', 'batch_number'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouses', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['warehouse_name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'استلام'), ('sale', 'صرف بيع'), ('bonus', 'صرف بونص'), ('consignment_out', 'صرف عهدة'), ('consignment_return', 'مرتجع عهدة'), ('customer_return', 'مرتجع عميل'), ('damage', 'إتلاف'), ('adjustment_in', 'تسوية إضافة'), ('adjustment_out', 'تسوية نقص')], max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_available', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_reserved', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_on_consignment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_rows', to='inventory.batch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_rows', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['product__product_name', 'batch__expiry_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'warehouse_name'), name='uniq_warehouse_per_company'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('company', 'warehouse', 'product', 'batch'), name='uniq_inventory_row_per_company'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('company', 'batch_number'), name='uniq_batch_number_per_company'),
        ),
    ]
