# Generated by Django 4.2.30 on 2026-08-11 21:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0001_initial'),
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(max_length=20)),
                ('collection_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_method', models.CharField(choices=[('cash_immediate', 'نقدي فوري'), ('cash_end_month', 'نقدي آخر الشهر'), ('instapay_immediate', 'إنستا باي فوري'), ('instapay_end_month', 'إنستا باي آخر الشهر'), ('fawry_immediate', 'محفظة فوري فوري'), ('fawry_end_month', 'محفظة فوري آخر الشهر'), ('bank_transfer', 'تحويل بنكي'), ('cheque', 'شيك')], max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_due_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='collections/%Y/%m/')),
                ('status', models.CharField(choices=[('confirmed', 'مؤكد'), ('pending', 'معلق'), ('pending_clearance', 'تحت التحصيل'), ('bounced', 'مرتجع'), ('cancelled', 'ملغي')], default='confirmed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.company')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_collections', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collections', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='customers.customer')),
            ],
            options={
                'db_table': 'collections',
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_applied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_links', to='customer_collections.collection')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_links', to='sales.invoice')),
            ],
            options={
                'db_table': 'collection_invoices',
            },
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('company', 'receipt_number'), name='uniq_receipt_number_per_company'),
        ),
    ]
