# Generated by Django 4.2.30 on 2026-08-11 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('core', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bonus_type', models.CharField(choices=[('none', 'بدون بونص'), ('quantity', 'كمية على كمية'), ('percentage', 'نسبة خصم'), ('fixed', 'عدد ثابت')], default='none', max_length=20)),
                ('buy_quantity', models.IntegerField(default=0)),
                ('free_quantity', models.IntegerField(default=0)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bonus_rules', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bonus_rules', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bonus_rules', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bonus_rules', to='products.product')),
            ],
            options={
                'db_table': 'customer_bonus_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bonus_type', models.CharField(choices=[('none', 'بدون بونص'), ('quantity', 'كمية على كمية'), ('percentage', 'نسبة خصم'), ('fixed', 'عدد ثابت')], default='none', max_length=20)),
                ('buy_quantity', models.IntegerField(default=0)),
                ('free_quantity', models.IntegerField(default=0)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules', to='products.product')),
            ],
            options={
                'db_table': 'bonus_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='customerbonusrule',
            constraint=models.UniqueConstraint(fields=('company', 'customer', 'product'), name='uniq_customer_bonus_rule'),
        ),
    ]
