# Generated by Django 4.2.30 on 2026-08-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerbonusrule',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
